Form setup
Alejandro-Bernal-M/Portfolio-setup-and-mobile-first pull request #5
Opened 2023-01-17 20:36 UTC by Alejandro-Bernal-M

Form setup ready.  Doing pair programming, we add the form section and the footer.

2023-01-17 21:02 UTC, huseyinbiyik requested changes
Hi @Alejandro-Bernal-M  and @matee-safi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Some of your image files are on the root folder. It is better to put under a folder like your other images. So your repo will look more organized. 👌

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 21:02 UTC, huseyinbiyik commented on styles.css
> +  /* justify-content: flex-start; */
Kindly don't leave any commented-out code, so your codebase will be neat and look more professional.👨‍💼

2023-01-17 21:02 UTC, huseyinbiyik commented on styles.css
> +}
Very good implementation of the given design but let's add some interaction and add hover and press state like on the design template. 
<img width="631" alt="Screenshot 2023-01-17 at 11 52 17 PM" src="https://user-images.githubusercontent.com/25887253/213010732-2e52f258-ad7d-4eec-8766-1b78513d2b38.png">

2023-01-17 22:13 UTC, Alejandro-Bernal-M commented
Hi @huseyinbiyik , thank you for the corrections. I changed the styles on the buttons, adding the :hover and :active pseudo-classes. And I put all the images into one folder. I'm asking for the other review.

2023-01-18 01:36 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @Alejandro-Bernal-M 

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 14:27 UTC, merged